# from matplotlib's azure setup

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/cache/pip

jobs:

- job: 'tests'
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-18.04
  container: debian:unstable
  strategy:
    matrix:
      static-checks:
        TOXENV: flake8,pylint,check-manifest,checkreadme
        SUNDIALS_VERSION: '4.1.0'
      main:
        TOXENV: py38
        SUNDIALS_VERSION: '4.1.0'

  steps:
    - template: ci_support/azure-pipelines-steps.yml
