steps:
- task: CacheBeta@0
  displayName: SUNDIALS cache
  inputs:
    key: SUNDIALS | "$(Agent.OS)" | "${{ parameters.vmImage }}" | "$(SUNDIALS_VERSION)"
    path: $(HOME)/sundials/
  condition: and(succeeded(), ne(variables['SUNDIALS_VERSION'], ''))

- task: CacheBeta@0
  displayName: pip cache
  inputs:
    key: pip | "$(Agent.OS)" | "${{ parameters.vmImage }}" | "$(SUNDIALS_VERSION)"
    path: $(PIP_CACHE_DIR)
  condition: and(succeeded(), ne(variables['SUNDIALS_VERSION'], ''))

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'
  condition: and(succeeded(), ne(variables['python.version'], 'Pre'))

- script: |
    python -m pip install --upgrade pip
    pip install tox codecov
  displayName: 'Install dependencies with pip'

- script: env
  displayName: 'print env'

- script: |
    tox
  displayName: 'tox'
  env: {"BASH_ENV": "./ci_support/ensure_sundials_installed.sh"}


- script: |
    codecov
  displayName: 'codecov'
