image: debian/unstable
packages:
# python
- python3-dev
- python3-tk
- python3-pip
#
- libsundials-dev # scikits.odes
- libhdf5-dev # h5py
- libgirepository1.0-dev # matplotlib/pygobject
- libgtk-3-dev # matplotlib/pygobject
#
- xvfb # headless testing

sources:
- https://git.sr.ht/~aragilar/DiscSolver

environment:
  PIPI: python3 -m pip install --user -U
  CODECOV_TOKEN: "879ba747-6e2f-4177-9cd9-4966dd876c0e"

tasks:
    - setup_path: |
        echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.buildenv
    - disable_manylinux: |
        /bin/echo $PATH
        cd DiscSolver
        sudo cp .builds/_manylinux.py /usr/lib/python3.7/_manylinux.py
    - deps_install: |
        cd DiscSolver
        $PIPI pip setuptools wheel
        $PIPI -c known_broken_constraints.txt --pre coverage # coverage major versions need to match
        $PIPI tox codecov
    - test: |
        cd DiscSolver
        tox
    - post_test: |
        cd DiscSolver
        codecov
triggers:
    - action: email
      condition: always
      to: james.tocknell@students.mq.edu.au
