# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: debian:unstable

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup APT
      run: |
        echo 'deb http://deb.debian.org/debian/ experimental main'
        apt update
        apt dist-upgrade

    - name: Install Dependencies via APT
      run: |
        # python
        apt install python3-dev
        apt install python3-tk
        apt install python3-pip
        #
        apt install libsundials-dev/experimental # scikits.odes
        apt install libhdf5-dev # h5py
        apt install libgirepository1.0-dev # matplotlib/pygobject
        apt install libgtk-3-dev # matplotlib/pygobject
        #
        apt install xvfb # headless testing

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Disable Manylinux:
      run: |
        sudo cp .builds/_manylinux.py /usr/lib/python3.8/_manylinux.py
    - name: Install Python Dependencies:
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -c known_broken_constraints.txt --pre coverage # coverage major versions need to match
        python -m pip install -U  tox codecov
    - name: test:
      run: |
        tox
    - name: upload coverage:
      run: |
        codecov
